# Generated by Django 5.0.3 on 2024-04-01 00:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendfaves',
            options={'verbose_name': 'Friend faves', 'verbose_name_plural': 'Friend faves'},
        ),
        migrations.AlterModelOptions(
            name='friendsuggestionsettings',
            options={'verbose_name': 'Friend suggestion settings', 'verbose_name_plural': 'Friend suggestion settings'},
        ),
        migrations.AddField(
            model_name='friend',
            name='first_meet_entered',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='suggestion_settings',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friend_friend_suggestion_settings', to='friends.friendsuggestionsettings'),
        ),
        migrations.AlterField(
            model_name='friendsuggestionsettings',
            name='effort_required',
            field=models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='friendsuggestionsettings',
            name='priority_level',
            field=models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='pastmeet',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
