# Generated by Django 5.0.3 on 2024-04-01 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_alter_friendfaves_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastmeet',
            name='type',
            field=models.CharField(choices=[('via text or social media', 'via text or social media'), ('in person', 'in person'), ('happenstance', 'happenstance'), ('unspecified', 'unspecified')], default='unspecified', max_length=50),
        ),
    ]
