# Generated by Django 5.0.3 on 2024-04-09 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0008_pastmeet_location_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thoughtcapsulez',
            options={'ordering': ('-category',)},
        ),
    ]
