# Generated by Django 5.0.3 on 2024-04-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0009_alter_thoughtcapsulez_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='times_used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
