# Generated by Django 5.0.3 on 2024-04-10 22:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0010_category_times_used'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pastmeet',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterField(
            model_name='friendsuggestionsettings',
            name='effort_required',
            field=models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='friendsuggestionsettings',
            name='priority_level',
            field=models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
