# Generated by Django 5.0.3 on 2024-04-11 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0012_location_calculate_distances_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='thought_capsule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='friends.thoughtcapsulez'),
        ),
    ]
