# Generated by Django 5.0.3 on 2024-04-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0013_alter_image_thought_capsule'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_notes',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
