# Generated by Django 5.0.3 on 2024-04-13 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0014_image_image_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastmeet',
            name='delete_all_unshared_capsules',
            field=models.BooleanField(default=False),
        ),
    ]
