# Generated by Django 5.0.3 on 2024-04-22 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0016_location_personal_experience_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ('-created_on',)},
        ),
    ]
