# Generated by Django 5.0.3 on 2024-06-14 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0021_friendaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendaddress',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='friends.friend'),
        ),
    ]
