# Generated by Django 5.0.3 on 2024-06-14 22:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0022_alter_friendaddress_friend'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendaddress',
            name='address',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='friendaddress',
            name='title',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='friendaddress',
            constraint=models.UniqueConstraint(fields=('friend', 'title'), name='unique_friend_title'),
        ),
        migrations.AddConstraint(
            model_name='friendaddress',
            constraint=models.UniqueConstraint(fields=('friend', 'address'), name='unique_friend_address'),
        ),
    ]
