# Generated by Django 5.0.3 on 2024-06-14 22:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0023_alter_friendaddress_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='friendaddress',
            name='unique_friend_title',
        ),
        migrations.RemoveConstraint(
            model_name='friendaddress',
            name='unique_friend_address',
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='title',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='friendaddress',
            unique_together={('friend', 'address'), ('friend', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('user', 'address'), ('user', 'title')},
        ),
    ]
