# Generated by Django 5.0.3 on 2024-07-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0024_remove_friendaddress_unique_friend_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='place_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
