# Generated by Django 5.0.3 on 2024-07-29 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0025_location_place_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
