# Generated by Django 5.0.3 on 2024-07-30 00:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0026_location_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('user', 'title', 'address')},
        ),
        migrations.AddField(
            model_name='location',
            name='parking_score',
            field=models.CharField(blank=True, choices=[('1', 'location has free parking lot'), ('2', 'free parking lot nearby'), ('3', 'street parking'), ('4', 'fairly stressful or unreliable street parking'), ('5', 'no parking whatsoever'), ('6', 'unspecified')], max_length=200, null=True),
        ),
    ]
