# Generated by Django 5.0.3 on 2024-07-30 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0027_alter_location_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendfaves',
            name='dark_color',
            field=models.CharField(blank=True, help_text='Hex color code for the dark theme', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='friendfaves',
            name='light_color',
            field=models.CharField(blank=True, help_text='Hex color code for the light theme', max_length=7, null=True),
        ),
    ]
