# Generated by Django 5.0.3 on 2024-07-31 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0028_friendfaves_dark_color_friendfaves_light_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendfaves',
            name='use_friend_color_theme',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
