# Generated by Django 5.0.3 on 2024-07-31 17:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0029_friendfaves_use_friend_color_theme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('user', 'title', 'address')},
        ),
        migrations.AddField(
            model_name='location',
            name='custom_title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('user', 'custom_title'), ('user', 'title', 'address')},
        ),
    ]
