# Generated by Django 5.0.3 on 2024-08-01 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0030_alter_location_unique_together_location_custom_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendfaves',
            name='second_color_option',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
