# Generated by Django 5.1 on 2024-08-30 21:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0031_friendfaves_second_color_option'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('-created_on',)},
        ),
        migrations.AlterModelOptions(
            name='pastmeet',
            options={'ordering': ('-date', '-created_on')},
        ),
        migrations.AddField(
            model_name='location',
            name='zip_code',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Zip code must be in either XXXXX or XXXXX-XXXXXX format', regex='^\\d{5}(-\\d{6})?$')]),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_notes',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='personal_experience_info',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='thoughtcapsulez',
            name='capsule',
            field=models.CharField(max_length=2000),
        ),
    ]
