# Generated by Django 5.1 on 2024-08-31 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0032_alter_image_options_alter_pastmeet_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thoughtcapsulez',
            name='capsule',
            field=models.CharField(max_length=10000),
        ),
    ]
