# Generated by Django 5.1 on 2024-09-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0033_alter_thoughtcapsulez_capsule'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastmeet',
            name='additional_notes',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
