# Generated by Django 5.1 on 2024-09-09 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0034_pastmeet_additional_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='thoughtcapsulez',
            options={'ordering': ('-category',), 'verbose_name': 'Moment (Thought Capsule)', 'verbose_name_plural': 'Moments (Thought Capsulez)'},
        ),
    ]
