# Generated by Django 5.1 on 2024-09-13 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0035_alter_category_options_alter_thoughtcapsulez_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nextmeet',
            options={'ordering': ('date', 'updated_on')},
        ),
    ]
