# Generated by Django 5.1 on 2024-09-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0036_alter_nextmeet_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='thoughtcapsulez',
            name='pre_added_to_hello',
            field=models.BooleanField(default=False),
        ),
    ]
