# Generated by Django 5.1 on 2024-09-27 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0037_thoughtcapsulez_pre_added_to_hello'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='parking_score',
            field=models.CharField(blank=True, choices=[('location has free parking lot', 'location has free parking lot'), ('free parking lot nearby', 'free parking lot nearby'), ('street parking', 'street parking'), ('fairly stressful or unreliable street parking', 'fairly stressful or unreliable street parking'), ('no parking whatsoever', 'no parking whatsoever'), ('unspecified', 'unspecified')], max_length=200, null=True),
        ),
    ]
