# Generated by Django 5.1 on 2024-10-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0038_alter_location_parking_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='theme_color_dark',
            field=models.CharField(blank=True, help_text='Hex color code for the dark theme', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='friend',
            name='theme_color_light',
            field=models.CharField(blank=True, help_text='Hex color code for the light theme', max_length=7, null=True),
        ),
    ]
