# Generated by Django 5.1 on 2024-11-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0039_friend_theme_color_dark_friend_theme_color_light'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='theme_color_font',
            field=models.CharField(blank=True, help_text='Hex color code for the primary font theme', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='friend',
            name='theme_color_font_secondary',
            field=models.CharField(blank=True, help_text='Hex color code for the secondary font theme', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='friendfaves',
            name='font_color',
            field=models.CharField(blank=True, help_text='Hex color code for the primary font theme', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='friendfaves',
            name='font_color_secondary',
            field=models.CharField(blank=True, help_text='Hex color code for the secondary font theme', max_length=7, null=True),
        ),
    ]
