# Generated by Django 5.1 on 2024-12-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0041_friend_saved_color_dark_friend_saved_color_light'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendaddress',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
