# Generated by Django 5.1 on 2025-05-14 22:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0043_pastmeet_updated_on'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['user'], name='friends_loc_user_id_c33f5e_idx'),
        ),
    ]
