# Generated by Django 5.1 on 2025-05-14 23:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0044_location_friends_loc_user_id_c33f5e_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pastmeet',
            index=models.Index(fields=['user', 'friend'], name='friends_pas_user_id_60dbe1_idx'),
        ),
    ]
