# Generated by Django 5.1 on 2025-05-14 23:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0045_pastmeet_friends_pas_user_id_60dbe1_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='nextmeet',
            index=models.Index(fields=['user', 'date'], name='friends_nex_user_id_9c240f_idx'),
        ),
        migrations.AddIndex(
            model_name='pastmeet',
            index=models.Index(fields=['friend'], name='friends_pas_friend__37b519_idx'),
        ),
        migrations.AddIndex(
            model_name='thoughtcapsulez',
            index=models.Index(fields=['friend'], name='friends_tho_friend__41f64b_idx'),
        ),
    ]
