# Generated by Django 5.1 on 2025-06-10 15:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0046_nextmeet_friends_nex_user_id_9c240f_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='updatestracker',
            index=models.Index(fields=['user'], name='friends_upd_user_id_6de2b0_idx'),
        ),
    ]
