# Generated by Django 5.1 on 2025-06-24 01:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0047_updatestracker_friends_upd_user_id_6de2b0_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendsuggestionsettings',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+123456789'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
