# Generated by Django 5.1 on 2025-06-29 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0048_friendsuggestionsettings_phone_number'),
        ('users', '0015_alter_usercategory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='user_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image', to='users.usercategory'),
        ),
        migrations.AddField(
            model_name='thoughtcapsulez',
            name='user_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thought_capsule', to='users.usercategory'),
        ),
    ]
