# Generated by Django 5.1 on 2025-06-30 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0049_image_user_category_thoughtcapsulez_user_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thoughtcapsulez',
            options={'ordering': ['user_category'], 'verbose_name': 'Moment (Thought Capsule)', 'verbose_name_plural': 'Moments (Thought Capsulez)'},
        ),
    ]
