# Generated by Django 5.1 on 2025-07-04 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0050_alter_thoughtcapsulez_options'),
        ('users', '0018_usercategory_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedThoughtCapsulez',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.CharField(blank=True, max_length=42, null=True)),
                ('capsule', models.CharField(max_length=10000)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user_category_name', models.CharField(blank=True, max_length=50, null=True)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friends.friend')),
                ('hello', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_capsules', to='friends.pastmeet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_thought_capsule', to='users.usercategory')),
            ],
            options={
                'verbose_name': 'Completed Moment (Thought Capsule)',
                'verbose_name_plural': 'Completed Moments (Thought Capsulez)',
                'ordering': ['user_category'],
                'indexes': [models.Index(fields=['friend'], name='friends_com_friend__41541b_idx')],
            },
        ),
    ]
