# Generated by Django 5.1 on 2025-07-10 14:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0052_rename_user_category_name_completedthoughtcapsulez_user_category_original_name'),
        ('users', '0019_usercategory_completed_thought_capsules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='completedthoughtcapsulez',
            index=models.Index(fields=['user'], name='friends_com_user_id_1a0c76_idx'),
        ),
        migrations.AddIndex(
            model_name='completedthoughtcapsulez',
            index=models.Index(fields=['user_category'], name='friends_com_user_ca_4b8377_idx'),
        ),
    ]
