# Generated by Django 5.1 on 2025-07-12 16:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0053_completedthoughtcapsulez_friends_com_user_id_1a0c76_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='friendsuggestionsettings',
            index=models.Index(fields=['user', 'friend'], name='friends_fri_user_id_b1f478_idx'),
        ),
    ]
