# Generated by Django 5.1 on 2025-07-12 17:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0054_friendsuggestionsettings_friends_fri_user_id_b1f478_idx'),
        ('users', '0020_alter_usercategory_completed_thought_capsules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='thoughtcapsulez',
            name='friends_tho_friend__41f64b_idx',
        ),
        migrations.AddIndex(
            model_name='thoughtcapsulez',
            index=models.Index(fields=['user', 'friend'], name='friends_tho_user_id_606f5a_idx'),
        ),
    ]
