# Generated by Django 5.1 on 2025-07-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0055_remove_thoughtcapsulez_friends_tho_friend__41f64b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedthoughtcapsulez',
            name='time_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
