# Generated by Django 5.1 on 2025-08-01 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0056_completedthoughtcapsulez_time_score'),
        ('users', '0021_usersettings_user_default_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendfaves',
            name='friend_default_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.usercategory'),
        ),
    ]
