# Generated by Django 5.1 on 2025-08-02 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0057_friendfaves_friend_default_category'),
        ('users', '0021_usersettings_user_default_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendfaves',
            name='friend_default_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friend_faves', to='users.usercategory'),
        ),
    ]
