# Generated by Django 5.1 on 2025-08-10 15:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0058_alter_friendfaves_friend_default_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pastmeet',
            name='friends_pas_friend__37b519_idx',
        ),
        migrations.AddIndex(
            model_name='pastmeet',
            index=models.Index(fields=['friend', '-date'], name='friends_pas_friend__55aafb_idx'),
        ),
    ]
