# Generated by Django 5.1 on 2025-08-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0060_voidedmeet'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextmeet',
            name='last_missed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nextmeet',
            name='last_voided_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nextmeet',
            name='miss_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nextmeet',
            name='void_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
