# Generated by Django 5.1 on 2025-09-22 23:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0061_nextmeet_last_missed_date_nextmeet_last_voided_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastmeet',
            name='freeze_effort_required',
            field=models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='pastmeet',
            name='freeze_priority_level',
            field=models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
