# Generated by Django 5.1 on 2025-10-26 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0062_pastmeet_freeze_effort_required_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thoughtcapsulez',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
