# Generated by Django 5.1 on 2026-01-11 16:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0063_remove_thoughtcapsulez_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='thoughtcapsulez',
            name='screen_x',
            field=models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='thoughtcapsulez',
            name='screen_y',
            field=models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
