# Generated by Django 5.1 on 2026-01-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0064_thoughtcapsulez_screen_x_thoughtcapsulez_screen_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='thoughtcapsulez',
            name='stored_index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
