# Generated by Django 5.1 on 2026-02-20 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0067_friendpicksession'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendpicksession',
            name='dark_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='friendpicksession',
            name='light_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
