# Generated by Django 5.1 on 2026-03-02 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0068_friendpicksession_dark_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendfaves',
            name='saved_color_dark',
            field=models.CharField(blank=True, help_text='Hex color code for saved dark theme', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='friendfaves',
            name='saved_color_light',
            field=models.CharField(blank=True, help_text='Hex color code for saved light theme', max_length=7, null=True),
        ),
    ]
