# Generated by Django 5.1 on 2026-03-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0069_friendfaves_saved_color_dark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='dashboard_last_viewed',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
