# Generated by Django 5.1 on 2026-03-23 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0071_geckodata_friend_gecko_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='geckodata',
            name='total_distance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
