# Generated by Django 5.1 on 2026-03-26 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0074_geckodatasession'),
    ]

    operations = [
        migrations.AddField(
            model_name='geckodata',
            name='total_duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='geckodatadaily',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
