# Generated by Django 5.1 on 2026-03-30 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0075_geckodata_total_duration_geckodatadaily_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friend',
            options={'ordering': ('next_meet__date',)},
        ),
    ]
