# Generated by Django 5.1 on 2026-03-30 23:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0076_alter_friend_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='geckodatasession',
            index=models.Index(fields=['user', 'friend'], name='friends_gec_user_id_8b3ce0_idx'),
        ),
        migrations.AddIndex(
            model_name='geckodatasession',
            index=models.Index(fields=['user', 'started_on'], name='friends_gec_user_id_912cb8_idx'),
        ),
    ]
