# Generated by Django 5.1 on 2026-04-02 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0077_geckodatasession_friends_gec_user_id_8b3ce0_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geckodata',
            name='total_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='geckodatasession',
            name='points_earned',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='GeckoDataDaily',
        ),
    ]
