# Generated by Django 5.1 on 2026-04-25 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0079_alter_friend_unique_together_friend_linked_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thoughtcapsulez',
            name='easy_score',
        ),
        migrations.RemoveField(
            model_name='thoughtcapsulez',
            name='generic_score',
        ),
        migrations.RemoveField(
            model_name='thoughtcapsulez',
            name='hard_score',
        ),
        migrations.RemoveField(
            model_name='thoughtcapsulez',
            name='long_score',
        ),
        migrations.RemoveField(
            model_name='thoughtcapsulez',
            name='quick_score',
        ),
        migrations.RemoveField(
            model_name='thoughtcapsulez',
            name='random_score',
        ),
        migrations.RemoveField(
            model_name='thoughtcapsulez',
            name='relevant_score',
        ),
        migrations.RemoveField(
            model_name='thoughtcapsulez',
            name='unique_score',
        ),
        migrations.AddField(
            model_name='friend',
            name='hidden_game_options_unlocked_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thoughtcapsulez',
            name='gecko_game_type',
            field=models.IntegerField(choices=[(1, 'Not gameable'), (2, 'A compliment'), (3, 'You impressed me when...'), (4, 'I was jealous of you when...'), (5, 'I was happy for you when...'), (6, 'You made me happy when...'), (7, 'It was really funny that time you...'), (8, "I don't like this thing but you do: "), (9, 'A shared interest'), (10, 'Something about me you might not know'), (11, 'I have always wanted to apologize for...')], default=1),
        ),
        migrations.AddField(
            model_name='thoughtcapsulez',
            name='match_only',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CapsuleDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capsule', models.CharField(max_length=10000)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_on'],
            },
        ),
    ]
