# Generated by Django 5.1 on 2026-05-10 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0080_remove_thoughtcapsulez_easy_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geckodatasession',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='geckodatasession',
            name='user',
        ),
    ]
