# Generated by Django 5.1 on 2026-05-10 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0081_remove_geckodatasession_friend_and_more'),
        ('users', '0064_remove_geckopointsledger_friend_session_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeckoDataSession',
        ),
    ]
