# Generated by Django 5.1 on 2026-05-25 20:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0082_delete_geckodatasession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pastmeet',
            name='session_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pastmeet',
            name='type',
            field=models.CharField(choices=[('via text or social media', 'via text or social media'), ('in person', 'in person'), ('happenstance', 'happenstance'), ('unspecified', 'unspecified'), ('gecko game', 'gecko game')], default='unspecified', max_length=50),
        ),
        migrations.AddIndex(
            model_name='pastmeet',
            index=models.Index(fields=['user', 'session_id'], name='friends_pas_user_id_1c0335_idx'),
        ),
    ]
