# Generated by Django 5.0.3 on 2024-05-12 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='badrainbowzuser',
            name='app_setup_complete',
            field=models.BooleanField(default=False),
        ),
    ]
