# Generated by Django 5.0.3 on 2024-06-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_badrainbowzuser_app_setup_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='addresses',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('NB', 'Non-Binary'), ('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('No answer', 'No answer')], default='', max_length=10, verbose_name='gender'),
        ),
    ]
