# Generated by Django 5.0.3 on 2024-07-29 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_useraddress_unique_user_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='simplify_app_for_focus',
            field=models.BooleanField(default=False),
        ),
    ]
