# Generated by Django 5.0.3 on 2024-07-31 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_usersettings_simplify_app_for_focus'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='manual_dark_mode',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
