# Generated by Django 5.1 on 2024-09-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_usersettings_manual_dark_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='badrainbowzuser',
            name='is_test_user',
            field=models.BooleanField(default=False),
        ),
    ]
