# Generated by Django 5.1 on 2025-01-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_useraddress_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='badrainbowzuser',
            name='code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='badrainbowzuser',
            name='password_reset_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
