# Generated by Django 5.1 on 2025-05-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_badrainbowzuser_code_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='badrainbowzuser',
            name='is_subscribed_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='badrainbowzuser',
            name='subscription_expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='badrainbowzuser',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
