# Generated by Django 5.1 on 2025-06-29 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0048_friendsuggestionsettings_phone_number'),
        ('users', '0013_badrainbowzuser_is_subscribed_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('max_active', models.PositiveIntegerField(default=20)),
                ('is_in_top_five', models.BooleanField(default=False)),
                ('images', models.ManyToManyField(blank=True, null=True, related_name='user_categories', to='friends.image')),
                ('thought_capsules', models.ManyToManyField(blank=True, null=True, related_name='user_categories', to='friends.thoughtcapsulez')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_category', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Category',
                'verbose_name_plural': 'User Categories',
                'ordering': ('name',),
            },
        ),
    ]
