# Generated by Django 5.1 on 2025-06-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0050_alter_thoughtcapsulez_options'),
        ('users', '0015_alter_usercategory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercategory',
            name='is_deletable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='usercategory',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_user_category_name'),
        ),
    ]
