# Generated by Django 5.1 on 2025-06-30 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_usercategory_is_deletable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercategory',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
