# Generated by Django 5.1 on 2025-07-02 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_usercategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercategory',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
