# Generated by Django 5.1 on 2025-07-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0051_completedthoughtcapsulez'),
        ('users', '0018_usercategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercategory',
            name='completed_thought_capsules',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_categories', to='friends.completedthoughtcapsulez'),
        ),
    ]
