# Generated by Django 5.1 on 2025-07-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0053_completedthoughtcapsulez_friends_com_user_id_1a0c76_idx_and_more'),
        ('users', '0019_usercategory_completed_thought_capsules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercategory',
            name='completed_thought_capsules',
            field=models.ManyToManyField(blank=True, related_name='user_categories', to='friends.completedthoughtcapsulez'),
        ),
    ]
