# Generated by Django 5.1 on 2025-08-01 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_usercategory_completed_thought_capsules'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='user_default_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.usercategory'),
        ),
    ]
