# Generated by Django 5.1 on 2025-08-02 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_usersettings_user_default_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='user_default_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.usercategory'),
        ),
    ]
