# Generated by Django 5.1 on 2025-09-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_usersettings_user_default_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='lock_in_custom_string',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='lock_in_next',
            field=models.BooleanField(default=False),
        ),
    ]
