# Generated by Django 5.1 on 2026-03-07 17:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0069_friendfaves_saved_color_dark_and_more'),
        ('users', '0024_userprofile_total_points_pointsledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='pinned_friend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pinned_in_settings', to='friends.friend'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='upcoming_friend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upcoming_in_settings', to='friends.friend'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='use_auto_select',
            field=models.BooleanField(default=False),
        ),
    ]
