# Generated by Django 5.1 on 2026-03-21 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0069_friendfaves_saved_color_dark_and_more'),
        ('users', '0025_usersettings_created_on_usersettings_pinned_friend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='new_friend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_friend_in_settings', to='friends.friend'),
        ),
    ]
