# Generated by Django 5.1 on 2026-03-25 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_geckocombineddata_geckocombineddaily'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geckocombineddaily',
            options={'ordering': ['-date']},
        ),
        migrations.CreateModel(
            name='GeckoCombinedSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steps', models.PositiveIntegerField(default=0)),
                ('distance', models.PositiveIntegerField(default=0)),
                ('started_on', models.DateTimeField()),
                ('ended_on', models.DateTimeField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_on'],
            },
        ),
    ]
