# Generated by Django 5.1 on 2026-03-26 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_geckocombineddaily_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geckocombineddaily',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='geckocombineddata',
            name='total_duration',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
