# Generated by Django 5.1 on 2026-03-28 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_geckocombineddaily_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeckoConfigs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personality_type', models.IntegerField(choices=[(1, 'Curious'), (2, 'Scientific'), (3, 'Brave')], default=1)),
                ('memory_type', models.IntegerField(choices=[(1, 'Amnesiac'), (2, 'Remember Some'), (3, 'Remember Many')], default=1)),
                ('active_hours_type', models.IntegerField(choices=[(1, 'Day'), (2, 'Night'), (3, 'Random')], default=1)),
                ('story_type', models.IntegerField(choices=[(1, 'Learner'), (2, 'Nommer'), (3, 'Escaper')], default=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geckoconfigs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
