# Generated by Django 5.1 on 2026-03-29 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0075_geckodata_total_duration_geckodatadaily_duration'),
        ('users', '0030_geckoconfigs'),
    ]

    operations = [
        migrations.AddField(
            model_name='geckocombinedsession',
            name='friend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='friends.friend'),
        ),
    ]
