# Generated by Django 5.1 on 2026-03-30 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0077_geckodatasession_friends_gec_user_id_8b3ce0_idx_and_more'),
        ('users', '0031_geckocombinedsession_friend'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='geckocombinedsession',
            index=models.Index(fields=['user'], name='users_gecko_user_id_1990ea_idx'),
        ),
        migrations.AddIndex(
            model_name='geckocombinedsession',
            index=models.Index(fields=['user', 'started_on'], name='users_gecko_user_id_995f64_idx'),
        ),
    ]
