# Generated by Django 5.1 on 2026-03-31 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_geckocombinedsession_users_gecko_user_id_1990ea_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badrainbowzuser',
            name='password_reset_code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
