# Generated by Django 5.1 on 2026-04-02 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0078_geckodata_total_points_and_more'),
        ('users', '0033_alter_badrainbowzuser_password_reset_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='geckocombineddata',
            name='total_gecko_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='geckocombinedsession',
            name='points_earned',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='GeckoPointsLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('reason', models.CharField(blank=True, max_length=100)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('friend', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='friends.friend')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gecko_points_ledger', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.DeleteModel(
            name='GeckoCombinedDaily',
        ),
    ]
