# Generated by Django 5.1 on 2026-04-02 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_geckocombineddata_total_gecko_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geckocombinedsession',
            name='points_earned',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
