# Generated by Django 5.1 on 2026-04-04 18:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_alter_geckocombinedsession_points_earned'),
    ]

    operations = [
        migrations.AddField(
            model_name='geckoconfigs',
            name='active_hours',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='geckoconfigs',
            name='max_active_hours',
            field=models.SmallIntegerField(default=16, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.CreateModel(
            name='ActiveHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activehours', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
