# Generated by Django 5.1 on 2026-04-04 22:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_geckoconfigs_active_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeckoSleepChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_hours_type', models.IntegerField(choices=[(1, 'Day'), (2, 'Night'), (3, 'Random')], default=1)),
                ('max_active_hours', models.SmallIntegerField(default=16, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('active_hours', models.JSONField(blank=True, default=list)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gecko_sleep_change_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.DeleteModel(
            name='ActiveHours',
        ),
        migrations.AddIndex(
            model_name='geckosleepchangelog',
            index=models.Index(fields=['user', 'created_on'], name='users_gecko_user_id_2d300f_idx'),
        ),
    ]
