# Generated by Django 5.1 on 2026-04-05 17:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0078_geckodata_total_points_and_more'),
        ('users', '0037_geckosleepchangelog_delete_activehours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geckopointsledger',
            name='combined_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_ledger_entries', to='users.geckocombinedsession'),
        ),
        migrations.AddField(
            model_name='geckopointsledger',
            name='friend_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_ledger_entries', to='friends.geckodatasession'),
        ),
        migrations.AddField(
            model_name='geckopointsledger',
            name='timestamp_earned',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
