# Generated by Django 5.1 on 2026-04-05 18:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_geckopointsledger_combined_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geckoconfigs',
            name='max_score_multiplier',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.CreateModel(
            name='GeckoScoreState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_multiplier', models.PositiveIntegerField(default=1)),
                ('multiplier', models.PositiveIntegerField(default=1)),
                ('expires_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geckoscorestate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
