# Generated by Django 5.1 on 2026-04-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_geckoconfigs_max_score_multiplier_geckoscorestate'),
    ]

    operations = [
        migrations.AddField(
            model_name='geckoconfigs',
            name='max_streak_length_seconds',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
