# Generated by Django 5.1 on 2026-04-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_geckoconfigs_max_streak_length_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='geckopointsledger',
            name='code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geckopointsledger',
            name='multiplier',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
