# Generated by Django 5.1 on 2026-04-05 23:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0078_geckodata_total_points_and_more'),
        ('users', '0041_geckopointsledger_code_geckopointsledger_multiplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='geckoconfigs',
            name='stamina',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='geckoscorestate',
            name='energy',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='geckoscorestate',
            name='energy_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='geckoscorestate',
            name='surplus_energy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='geckoconfigs',
            name='max_streak_length_seconds',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddIndex(
            model_name='geckocombinedsession',
            index=models.Index(fields=['user', 'ended_on'], name='users_gecko_user_id_b01c3d_idx'),
        ),
    ]
