# Generated by Django 5.1 on 2026-04-06 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0078_geckodata_total_points_and_more'),
        ('users', '0042_geckoconfigs_stamina_geckoscorestate_energy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geckoconfigs',
            name='max_duration_till_revival',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='geckoscorestate',
            name='revives_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GeckoEnergyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy', models.FloatField()),
                ('surplus_energy', models.FloatField()),
                ('steps', models.PositiveIntegerField(default=0)),
                ('recorded_at', models.DateTimeField()),
                ('friend', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='friends.friend')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geckoenergylog_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'recorded_at'], name='users_gecko_user_id_ec6efe_idx')],
            },
        ),
    ]
