# Generated by Django 5.1 on 2026-04-06 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_geckoconfigs_max_duration_till_revival_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geckoenergylog',
            name='total_steps',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
