# Generated by Django 5.1 on 2026-04-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_geckoenergylog_total_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='geckoscorestate',
            name='active_hours',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='geckoscorestate',
            name='active_hours_type',
            field=models.IntegerField(choices=[(1, 'Day'), (2, 'Night'), (3, 'Random')], default=1),
        ),
        migrations.AddField(
            model_name='geckoscorestate',
            name='gecko_created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geckoscorestate',
            name='max_active_hours',
            field=models.SmallIntegerField(default=16),
        ),
        migrations.AddField(
            model_name='geckoscorestate',
            name='max_duration_till_revival',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='geckoscorestate',
            name='max_score_multiplier',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='geckoscorestate',
            name='max_streak_length_seconds',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='geckoscorestate',
            name='memory_type',
            field=models.IntegerField(choices=[(1, 'Amnesiac'), (2, 'Remember Some'), (3, 'Remember Many')], default=1),
        ),
        migrations.AddField(
            model_name='geckoscorestate',
            name='personality_type',
            field=models.IntegerField(choices=[(1, 'Curious'), (2, 'Scientific'), (3, 'Brave')], default=1),
        ),
        migrations.AddField(
            model_name='geckoscorestate',
            name='stamina',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='geckoscorestate',
            name='story_type',
            field=models.IntegerField(choices=[(1, 'Learner'), (2, 'Nommer'), (3, 'Escaper')], default=1),
        ),
    ]
