# Generated by Django 5.1 on 2026-04-11 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_geckoscorestate_active_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendLinkCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='friend_link_code', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeckoEnergySyncSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('trigger', models.CharField(max_length=32)),
                ('client_energy', models.FloatField(blank=True, null=True)),
                ('client_surplus', models.FloatField(blank=True, null=True)),
                ('client_multiplier', models.FloatField(blank=True, null=True)),
                ('client_computed_at', models.DateTimeField(blank=True, null=True)),
                ('client_steps_in_payload', models.IntegerField(blank=True, null=True)),
                ('client_distance_in_payload', models.FloatField(blank=True, null=True)),
                ('server_energy_before', models.FloatField()),
                ('server_energy_after', models.FloatField()),
                ('server_surplus_before', models.FloatField()),
                ('server_surplus_after', models.FloatField()),
                ('server_updated_at_before', models.DateTimeField()),
                ('server_updated_at_after', models.DateTimeField()),
                ('recompute_window_seconds', models.FloatField()),
                ('recompute_active_seconds', models.FloatField()),
                ('recompute_new_steps', models.IntegerField()),
                ('recompute_fatigue', models.FloatField()),
                ('recompute_recharge', models.FloatField()),
                ('recompute_net', models.FloatField()),
                ('pending_entries_count', models.IntegerField()),
                ('pending_entries_in_window', models.IntegerField()),
                ('pending_entries_stale', models.IntegerField()),
                ('pending_total_steps_all', models.IntegerField()),
                ('pending_total_steps_in_window', models.IntegerField()),
                ('energy_delta', models.FloatField(blank=True, db_index=True, null=True)),
                ('phantom_steps', models.IntegerField(blank=True, db_index=True, null=True)),
                ('multiplier_active', models.BooleanField(default=False)),
                ('streak_expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_sync_samples', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='users_gecko_user_id_47f8e1_idx'), models.Index(fields=['-phantom_steps'], name='users_gecko_phantom_6e1d7f_idx')],
            },
        ),
    ]
