# Generated by Django 5.1 on 2026-04-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_friendlinkcode_geckoenergysyncsample'),
    ]

    operations = [
        migrations.AddField(
            model_name='geckoenergysyncsample',
            name='total_steps_all_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
