# Generated by Django 5.1 on 2026-04-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_geckoenergysyncsample_total_steps_all_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='geckoenergysyncsample',
            name='client_ended_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geckoenergysyncsample',
            name='client_fatigue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geckoenergysyncsample',
            name='client_recharge',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geckoenergysyncsample',
            name='client_started_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
