# Generated by Django 5.1 on 2026-04-12 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_alter_friendlinkcode_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfriendcurrentlivesesh',
            name='current_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_seshes', to='users.userfriendliveseshlog'),
        ),
    ]
