# Generated by Django 5.1 on 2026-04-13 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0079_alter_friend_unique_together_friend_linked_user_and_more'),
        ('users', '0050_alter_userfriendcurrentlivesesh_current_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfriendcurrentlivesesh',
            name='friend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_live_seshes', to='friends.friend'),
        ),
    ]
