# Generated by Django 5.1 on 2026-04-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_userfriendcurrentlivesesh_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfriendliveseshinvite',
            name='invite_expires_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
