# Generated by Django 5.1 on 2026-04-23 23:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_userfriendliveseshinvite_invite_expires_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geckoscorestate',
            name='max_active_hours',
            field=models.SmallIntegerField(default=16, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
