# Generated by Django 5.1 on 2026-04-23 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_alter_geckoscorestate_max_active_hours'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeckoConfigs',
        ),
    ]
