# Generated by Django 5.1 on 2026-04-25 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0080_remove_thoughtcapsulez_easy_score_and_more'),
        ('users', '0054_delete_geckoconfigs'),
    ]

    operations = [
        migrations.AddField(
            model_name='geckoscorestate',
            name='use_game_type_capsules_only',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='GeckoGameWin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_capsule_id', models.UUIDField(blank=True, null=True)),
                ('capsule', models.CharField(max_length=10000)),
                ('gecko_game_type', models.PositiveSmallIntegerField()),
                ('gecko_game_type_label', models.CharField(max_length=64)),
                ('won_by_matching', models.BooleanField(default=False)),
                ('matched_capsule_id', models.UUIDField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('friend', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='friends.friend')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gecko_game_wins', to=settings.AUTH_USER_MODEL)),
                ('user_won_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gecko_game_wins_from', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
