# Generated by Django 5.1 on 2026-04-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_geckogamewinpending'),
    ]

    operations = [
        migrations.AddField(
            model_name='geckogamewinpending',
            name='match_key',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
