# Generated by Django 5.1 on 2026-04-27 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_geckogamewinpending_match_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='geckogamewinpending',
            name='gecko_game_type',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geckogamewinpending',
            name='gecko_game_type_label',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
