# Generated by Django 5.1 on 2026-04-27 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0080_remove_thoughtcapsulez_easy_score_and_more'),
        ('users', '0058_geckogamewinpending_gecko_game_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeckoGameMatchWinPending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gecko_game_type', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gecko_game_type_label', models.CharField(blank=True, max_length=64)),
                ('host_accepted_on', models.DateTimeField(blank=True, null=True)),
                ('guest_accepted_on', models.DateTimeField(blank=True, null=True)),
                ('finalized_on', models.DateTimeField(blank=True, null=True)),
                ('declined_on', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gecko_game_match_pending_guest', to=settings.AUTH_USER_MODEL)),
                ('guest_capsule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='friends.thoughtcapsulez')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gecko_game_match_pending_host', to=settings.AUTH_USER_MODEL)),
                ('host_capsule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='friends.thoughtcapsulez')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gecko_game_match_pending_initiated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
