# Generated by Django 5.1 on 2026-04-28 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0059_geckogamematchwinpending'),
    ]

    operations = [
        migrations.AddField(
            model_name='geckogamewin',
            name='pin_priority',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geckogamewin',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
