# Generated by Django 5.1 on 2026-04-29 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_geckogamewin_pin_priority_geckogamewin_pinned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geckogamewinpending',
            name='match_key',
        ),
    ]
