# Generated by Django 5.1 on 2026-04-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0061_remove_geckogamewinpending_match_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfriendcurrentlivesesh',
            name='gecko_play_mode',
            field=models.IntegerField(choices=[(1, 'Dig'), (2, 'Intuit')], default=1),
        ),
    ]
