# Generated by Django 5.1 on 2026-05-10 16:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0062_userfriendcurrentlivesesh_gecko_play_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='geckoscorestate',
            name='last_steak_expiry',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='geckoscorestate',
            name='steps_last_24h',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='geckoscorestate',
            name='sustenance_last_24th',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='geckoscorestate',
            name='total_distance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='geckoscorestate',
            name='total_duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='geckoscorestate',
            name='total_gecko_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='geckoscorestate',
            name='total_steps',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='GeckoHourlySteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.PositiveSmallIntegerField()),
                ('steps', models.PositiveIntegerField(default=0)),
                ('distance', models.PositiveIntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'hour')},
            },
        ),
    ]
