# Generated by Django 5.1 on 2026-05-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0081_remove_geckodatasession_friend_and_more'),
        ('users', '0063_geckoscorestate_last_steak_expiry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geckopointsledger',
            name='friend_session',
        ),
        migrations.AddIndex(
            model_name='geckocombinedsession',
            index=models.Index(fields=['user', 'friend'], name='users_gecko_user_id_bb162e_idx'),
        ),
    ]
