# Generated by Django 5.1 on 2026-05-10 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0064_remove_geckopointsledger_friend_session_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeckoCombinedData',
        ),
    ]
