# Generated by Django 5.1 on 2026-05-10 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0065_delete_geckocombineddata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geckoscorestate',
            name='steps_last_24h',
        ),
        migrations.RemoveField(
            model_name='geckoscorestate',
            name='sustenance_last_24th',
        ),
    ]
