# Generated by Django 5.1 on 2026-05-17 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0066_remove_geckoscorestate_steps_last_24h_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geckosleepchangelog',
            name='user',
        ),
        migrations.DeleteModel(
            name='GeckoEnergyLog',
        ),
        migrations.DeleteModel(
            name='GeckoSleepChangeLog',
        ),
    ]
