# Generated by Django 5.1 on 2026-05-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0067_remove_geckosleepchangelog_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfriendliveseshlog',
            name='guest_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userfriendliveseshlog',
            name='host_points',
            field=models.IntegerField(default=0),
        ),
    ]
