# Generated by Django 5.1 on 2026-05-17 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0068_userfriendliveseshlog_guest_points_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFriendLiveSeshPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('steps', models.PositiveIntegerField(default=0)),
                ('distance', models.PositiveIntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('sesh_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='side_points', to='users.userfriendliveseshlog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_sesh_side_points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['sesh_log', 'user'], name='users_userf_sesh_lo_06e954_idx')],
                'constraints': [models.UniqueConstraint(fields=('sesh_log', 'user'), name='uniq_seshlog_user_side')],
            },
        ),
    ]
