# Generated by Django 5.1 on 2026-05-17 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0069_userfriendliveseshpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='geckocombinedsession',
            name='live_sesh_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combined_sessions', to='users.userfriendliveseshlog'),
        ),
    ]
