# Generated by Django 5.1 on 2026-05-24 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0070_geckocombinedsession_live_sesh_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeckoEnergySyncSample',
        ),
    ]
