# Generated by Django 5.1 on 2026-05-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0071_delete_geckoenergysyncsample'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfriendcurrentlivesesh',
            name='session_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userfriendliveseshlog',
            name='session_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
