# Generated by Django 5.1 on 2026-05-25 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0072_userfriendcurrentlivesesh_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geckogamewin',
            name='session_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
