# Generated by Django 5.1 on 2026-05-27 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0073_geckogamewin_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLifetimeTotals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_steps', models.PositiveIntegerField(default=0)),
                ('total_distance', models.PositiveIntegerField(default=0)),
                ('total_duration', models.PositiveIntegerField(default=0)),
                ('total_gecko_points', models.PositiveIntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lifetime_totals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
