# Generated by Django 5.1 on 2026-05-27 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0083_pastmeet_session_id_alter_pastmeet_type_and_more'),
        ('users', '0074_userlifetimetotals'),
    ]

    operations = [
        migrations.AddField(
            model_name='geckopointsledger',
            name='past_meet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gecko_points_awarded', to='friends.pastmeet'),
        ),
    ]
