# Generated by Django 5.1 on 2026-05-31 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0075_geckopointsledger_past_meet'),
    ]

    operations = [
        migrations.AddField(
            model_name='geckoscorestate',
            name='color_gecko_body_0',
            field=models.CharField(blank=True, help_text='Hex color code for gecko body 0', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='geckoscorestate',
            name='color_gecko_outline_0',
            field=models.CharField(blank=True, help_text='Hex color code for gecko outline 0', max_length=7, null=True),
        ),
    ]
