# Generated by Django 5.1 on 2026-06-01 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0076_geckoscorestate_color_gecko_body_0_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfriendcurrentlivesesh',
            name='gecko_wins_this_session',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
