# Generated by Django 5.1 on 2026-06-05 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0077_userfriendcurrentlivesesh_gecko_wins_this_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfriendcurrentlivesesh',
            name='gecko_game_level',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2')], default=1),
        ),
    ]
