# Generated by Django 5.1 on 2026-06-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0078_userfriendcurrentlivesesh_gecko_game_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfriendcurrentlivesesh',
            name='gecko_game_level',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4')], default=1),
        ),
    ]
