# Generated by Django 5.1 on 2026-06-11 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0079_alter_userfriendcurrentlivesesh_gecko_game_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfriendcurrentlivesesh',
            name='last_session_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userfriendcurrentlivesesh',
            name='last_session_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userfriendcurrentlivesesh',
            name='total_play_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
