# Generated by Django 5.1 on 2026-06-12 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0080_userfriendcurrentlivesesh_last_session_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfriendcurrentlivesesh',
            name='total_progress_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
