# Generated by Django 5.1 on 2026-04-02 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Welcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('label', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('is_experimental', models.BooleanField(default=False)),
                ('is_easter_egg', models.BooleanField(default=False)),
                ('personality_curious', models.BooleanField(default=True)),
                ('personality_scientific', models.BooleanField(default=True)),
                ('personality_brave', models.BooleanField(default=True)),
                ('memory_amnesiac', models.BooleanField(default=True)),
                ('memory_remembersome', models.BooleanField(default=True)),
                ('memory_remembermany', models.BooleanField(default=True)),
                ('activity_hours_day', models.BooleanField(default=True)),
                ('activity_hours_night', models.BooleanField(default=True)),
                ('activity_hours_random', models.BooleanField(default=True)),
                ('story_learner', models.BooleanField(default=True)),
                ('story_nommer', models.BooleanField(default=True)),
                ('story_escaper', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
