# Generated by Django 5.1 on 2026-04-03 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geckoscripts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomeScriptLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shown_at', models.DateTimeField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('script', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='geckoscripts.welcome')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='welcome_script_ledger', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-shown_at'],
            },
        ),
    ]
