# Generated by Django 5.1 on 2026-04-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geckoscripts', '0002_welcomescriptledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('label', models.CharField(blank=True, max_length=128)),
                ('points', models.IntegerField(default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code', 'version'],
                'constraints': [models.UniqueConstraint(fields=('code', 'version'), name='unique_scorerule_code_version')],
            },
        ),
    ]
