# Generated by Django 5.1 on 2026-04-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geckoscripts', '0003_scorerule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorerule',
            name='code',
            field=models.PositiveIntegerField(),
        ),
    ]
